name: CI
on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install libsilo-dev openmpi-bin libopenmpi-dev
